export type ImportType = 'CLICKUP_BACKLOG' | 'CLICKUP_SPRINT' | 'GLPI_CSV' | 'UNKNOWN';
export type TaskSource = 'CLICKUP' | 'GLPI' | 'MANUAL';
export type NormalizedStatus = 'TODO' | 'IN_PROGRESS' | 'WAITING' | 'TESTING' | 'REVIEW' | 'DOCUMENTATION' | 'READY_FOR_DEPLOYMENT' | 'DONE' | 'CLOSED' | 'CANCELLED' | 'UNKNOWN';
export type NormalizedPriority = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'UNKNOWN';
export type TaskPriorityLevel = 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
export type DependencyStatus = 'NONE' | 'READY' | 'WAITING_PREDECESSOR' | 'BLOCKED_BY_DEPENDENCY' | 'CYCLIC_DEPENDENCY';
export type AbsenceReason = 'CONGE' | 'MALADIE' | 'FORMATION' | 'MISSION' | 'REUNION' | 'AUTRE';
export type SprintStatus = 'DRAFT' | 'ACTIVE' | 'CLOSED' | 'CANCELLED';
export type PlanningOrigin = 'AUTO' | 'MANUAL';
export type PlanningStatus = 'UNPLANNED' | 'AUTO_PLANNED' | 'MANUALLY_ADJUSTED' | 'LOCKED' | 'CONFLICT' | 'CANNOT_PLAN' | 'CARRIED_OVER' | 'WAITING_PREDECESSOR' | 'BLOCKED_BY_DEPENDENCY' | 'CYCLIC_DEPENDENCY';
export type PlanningTriggerEvent = 'TASK_PRIORITY_CHANGED' | 'TASK_DURATION_CHANGED' | 'TASK_STATUS_CHANGED' | 'TASK_ASSIGNEE_CHANGED' | 'RESOURCE_ABSENCE_ADDED' | 'RESOURCE_CAPACITY_CHANGED' | 'SPRINT_DATES_CHANGED' | 'SILO_PRIORITY_CHANGED' | 'NEW_TASK_IMPORTED' | 'TASK_LOCKED' | 'TASK_UNLOCKED' | 'MANUAL_ADJUSTMENT' | 'MANUAL_PRIORITY_CHANGED' | 'TASK_DEPENDENCY_ADDED' | 'TASK_DEPENDENCY_REMOVED' | 'DEPENDENCY_CONFLICT_DETECTED' | 'AUTO_REPLAN_REQUESTED' | 'DEMO_DATA_LOADED';

export interface PrioritizationScores { businessImpact: number; regulatoryUrgency: number; vipRequest: number; userValue: number; riskReduction: number; projectMaturity: number; costComplexity: number; resourceAvailability: number; }
export interface TaskPrioritization { businessImpact: string; regulatoryUrgency: string; vipRequest: string; userValue: string; riskReduction: string; projectMaturity: string; estimatedCostComplexity: string; resourceAvailability: string; businessImpactScore: number; regulatoryUrgencyScore: number; vipRequestScore: number; userValueScore: number; riskReductionScore: number; projectMaturityScore: number; estimatedCostComplexityScore: number; resourceAvailabilityScore: number; totalPriorityScore: number; }
export interface Task { id: string; source: TaskSource; importType: ImportType; externalId: string; displayExternalId: string; title: string; description?: string | null; taskType?: string | null; type?: string | null; siloId?: string | null; siloName?: string | null; assigneeId?: string | null; assigneeName?: string | null; assigneeNames?: string[]; requesterName?: string | null; assignmentGroup?: string | null; assignmentGroups?: string[]; category?: string | null; statusRaw?: string | null; statusNormalized: NormalizedStatus; priorityRaw?: string | null; priorityNormalized: NormalizedPriority; priority?: string | null; urgency?: string | null; impact?: string | null; visibility?: string | null; estimatedHours?: number | null; remainingHours?: number | null; startDate?: string | null; dueDate?: string | null; createdAtSource?: string | null; updatedAtSource?: string | null; closedAtSource?: string | null; resolvedAtSource?: string | null; doneAtSource?: string | null; importedAt: string; parentExternalId?: string | null; parentName?: string | null; parentUrl?: string | null; sprintNames?: string | null; metadata: Record<string, unknown>; locked: boolean; manuallyAdjusted: boolean; prioritization: TaskPrioritization; automaticPriorityScore: number; effectivePriorityScore: number; priorityLevel: TaskPriorityLevel; manualPriorityRank?: number | null; manualPriorityEnabled: boolean; manualPriorityReason?: string | null; effectivePriorityRank?: number | null; predecessorTaskIds: string[]; successorTaskIds: string[]; dependencyStatus: DependencyStatus; planningStatus?: PlanningStatus; unplannedReason?: string | null; }
export interface WorkSilo { id: string; name: string; description?: string | null; priority: number; dailyCapacityPercent: number; sprintCapacityPercent: number; minimumDailyHours: number; maxWorkInProgress: number; active: boolean; }
export interface Resource { id: string; fullName: string; role?: string | null; dailyCapacityHours: number; weeklyCapacityHours: number; active: boolean; }
export interface Absence { id: string; resourceId: string; startDate: string; endDate: string; reason: AbsenceReason; comment?: string | null; }
export interface Sprint { id: string; name: string; startDate: string; endDate: string; status: SprintStatus; goal?: string | null; totalCapacityHours: number; planifiableCapacityHours: number; bufferCapacityHours: number; createdAt: string; updatedAt: string; }
export interface SprintTask { id: string; sprintId: string; taskId: string; siloId?: string | null; assigneeId?: string | null; estimatedHours: number; plannedHours: number; remainingHours: number; plannedStartDate?: string | null; plannedEndDate?: string | null; score: number; status: NormalizedStatus; planningOrigin: PlanningOrigin; planningStatus: PlanningStatus; locked: boolean; manuallyAdjusted: boolean; carriedOver: boolean; createdAt: string; updatedAt: string; }
export interface SprintPlanningSlot { id: string; sprintId: string; sprintTaskId: string; taskId: string; resourceId: string; siloId?: string | null; date: string; plannedHours: number; generatedBy: 'AUTO_PLANNING' | 'MANUAL'; }
export interface TaskDependency { id: string; predecessorTaskId: string; successorTaskId: string; type: 'FINISH_TO_START'; mandatory: boolean; createdAt: string; }
export interface PlanningRevision { id: string; revisionDate: string; triggerEvent: PlanningTriggerEvent; description: string; impactedTaskIds: string[]; impactedSprintIds: string[]; changesCount: number; }
export interface PlanningChange { id: string; revisionId: string; taskId: string; oldSprintId?: string | null; newSprintId?: string | null; oldAssigneeId?: string | null; newAssigneeId?: string | null; oldStartDate?: string | null; newStartDate?: string | null; oldEndDate?: string | null; newEndDate?: string | null; reason: string; }
export interface ImportSession { id: string; importDate: string; fileName: string; importType: ImportType; source: TaskSource; totalRows: number; importedRows: number; ignoredRows: number; errorRows: number; status: 'SUCCESS' | 'PARTIAL' | 'ERROR'; recognizedColumns?: string[]; unknownColumns?: string[]; }
export interface ImportError { id: string; importSessionId: string; rowNumber: number; columnName?: string | null; rawValue?: unknown; errorMessage: string; }
export interface ImportPreview { type: ImportType; rows: Record<string, unknown>[]; recognizedColumns: string[]; unknownColumns: string[]; totalRows: number; }
export interface PlanningResult { revision: PlanningRevision; sprintTasks: SprintTask[]; slots: SprintPlanningSlot[]; unplannedTasks: Task[]; changes: PlanningChange[]; }
